name: aks-qa-deploy
on:
  pull_request:
    branches: [ develop ]

env:
  IMAGE_HOST: ghcr.io/${{ github.repository }}
  IMAGE_NAME: blog-service
  IMAGE_TAG: ${{ github.sha }}
  NAMESPACE: qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: repo checkout
      uses: actions/checkout@v3

    - name: build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: log into registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: push image
      run: |
        docker tag $IMAGE_NAME $IMAGE_HOST/$IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_HOST/$IMAGE_NAME:$IMAGE_TAG