apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: ghcr.io/baobab-kr/blog-service/blog-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          resources:
            requests:
              cpu: 5m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: blog-service